package mux

// Common MIME content type constants.
//
// See: https://www.iana.org/assignments/media-types/media-types.xhtml
const (
	// Application types.
	ContentTypeApplicationJSON           = "application/json"
	ContentTypeApplicationJSONUTF8       = "application/json; charset=utf-8"
	ContentTypeApplicationJSONLD         = "application/ld+json"
	ContentTypeApplicationNDJSON         = "application/x-ndjson"
	ContentTypeApplicationHALJSON        = "application/hal+json"
	ContentTypeApplicationJWT            = "application/jwt"
	ContentTypeApplicationJWKJSON        = "application/jwk+json"
	ContentTypeApplicationJWKSetJSON     = "application/jwk-set+json"
	ContentTypeApplicationMergePatchJSON = "application/merge-patch+json"
	ContentTypeApplicationJSONPatchJSON  = "application/json-patch+json"
	ContentTypeApplicationProblemJSON    = "application/problem+json"
	ContentTypeApplicationProblemXML     = "application/problem+xml"
	ContentTypeApplicationReportsJSON    = "application/reports+json"
	ContentTypeApplicationCSPReport      = "application/csp-report"
	ContentTypeApplicationXML            = "application/xml"
	ContentTypeApplicationXHTMLXML       = "application/xhtml+xml"
	ContentTypeApplicationSOAPXML        = "application/soap+xml"
	ContentTypeApplicationAtomXML        = "application/atom+xml"
	ContentTypeApplicationRSSXML         = "application/rss+xml"
	ContentTypeApplicationManifestJSON   = "application/manifest+json"
	ContentTypeApplicationFormURLEncoded = "application/x-www-form-urlencoded"
	ContentTypeApplicationOctetStream    = "application/octet-stream"
	ContentTypeApplicationPDF            = "application/pdf"
	ContentTypeApplicationRTF            = "application/rtf"
	ContentTypeApplicationWASM           = "application/wasm"
	ContentTypeApplicationMP4            = "application/mp4"
	ContentTypeApplicationSQL            = "application/sql"
	ContentTypeApplicationGraphQL        = "application/graphql"
	ContentTypeApplicationProtobuf       = "application/protobuf"
	ContentTypeApplicationXProtobuf      = "application/x-protobuf"
	ContentTypeApplicationGRPC           = "application/grpc"
	ContentTypeApplicationCBOR           = "application/cbor"
	ContentTypeApplicationZip            = "application/zip"
	ContentTypeApplicationGzip           = "application/gzip"
	ContentTypeApplicationTar            = "application/x-tar"
	ContentTypeApplicationJavaScript     = "application/javascript"
	ContentTypeApplicationYAML           = "application/x-yaml"
	ContentTypeApplicationTOML           = "application/toml"
	ContentTypeApplicationZstd           = "application/zstd"
	ContentTypeApplicationXGzip          = "application/x-gzip"
	ContentTypeApplicationXBzip2         = "application/x-bzip2"
	ContentTypeApplicationXXZ            = "application/x-xz"
	ContentTypeApplicationX7ZCompressed  = "application/x-7z-compressed"
	ContentTypeApplicationXRARCompressed = "application/x-rar-compressed"
	ContentTypeApplicationPKCS7Mime      = "application/pkcs7-mime"
	ContentTypeApplicationPKCS8          = "application/pkcs8"
	ContentTypeApplicationPKCS10         = "application/pkcs10"
	ContentTypeApplicationPKIXCert       = "application/pkix-cert"
	ContentTypeApplicationPKIXCRL        = "application/pkix-crl"
	ContentTypeApplicationOCSPRequest    = "application/ocsp-request"
	ContentTypeApplicationOCSPResponse   = "application/ocsp-response"
	ContentTypeApplicationXPEMFile       = "application/x-pem-file"
	ContentTypeApplicationVndAPIJSON     = "application/vnd.api+json"

	// Multipart types.
	ContentTypeMultipartFormData = "multipart/form-data"
	ContentTypeMultipartMixed    = "multipart/mixed"
	ContentTypeMultipartByteRng  = "multipart/byteranges"

	// Message types.
	ContentTypeMessageHTTP = "message/http"
	ContentTypeMessageRFC  = "message/rfc822"

	// Text types.
	ContentTypeTextPlain       = "text/plain"
	ContentTypeTextPlainUTF8   = "text/plain; charset=utf-8"
	ContentTypeTextHTML        = "text/html"
	ContentTypeTextHTMLUTF8    = "text/html; charset=utf-8"
	ContentTypeTextCSS         = "text/css"
	ContentTypeTextCSV         = "text/csv"
	ContentTypeTextXML         = "text/xml"
	ContentTypeTextJavaScript  = "text/javascript"
	ContentTypeTextMarkdown    = "text/markdown"
	ContentTypeTextYAML        = "text/yaml"
	ContentTypeTextCalendar    = "text/calendar"
	ContentTypeTextVCard       = "text/vcard"
	ContentTypeTextEventStream = "text/event-stream"

	// Image types.
	ContentTypeImagePNG    = "image/png"
	ContentTypeImageJPEG   = "image/jpeg"
	ContentTypeImageGIF    = "image/gif"
	ContentTypeImageWebP   = "image/webp"
	ContentTypeImageAVIF   = "image/avif"
	ContentTypeImageBMP    = "image/bmp"
	ContentTypeImageTIFF   = "image/tiff"
	ContentTypeImageICO    = "image/vnd.microsoft.icon"
	ContentTypeImageXIcon  = "image/x-icon"
	ContentTypeImageHEIC   = "image/heic"
	ContentTypeImageSVGXML = "image/svg+xml"

	// Audio types.
	ContentTypeAudioMPEG = "audio/mpeg"
	ContentTypeAudioMP4  = "audio/mp4"
	ContentTypeAudioOGG  = "audio/ogg"
	ContentTypeAudioWAV  = "audio/wav"
	ContentTypeAudioWebM = "audio/webm"
	ContentTypeAudioAAC  = "audio/aac"
	ContentTypeAudioFLAC = "audio/flac"
	ContentTypeAudioOpus = "audio/opus"

	// Video types.
	ContentTypeVideoMP4       = "video/mp4"
	ContentTypeVideoMPEG      = "video/mpeg"
	ContentTypeVideoOGG       = "video/ogg"
	ContentTypeVideoWebM      = "video/webm"
	ContentTypeVideoMP2T      = "video/mp2t"
	ContentTypeVideoISOSeg    = "video/iso.segment"
	ContentTypeVideoAVI       = "video/x-msvideo"
	ContentTypeVideoQuickTime = "video/quicktime"

	// Adaptive streaming types.
	ContentTypeAppleMpegURL = "application/vnd.apple.mpegurl"
	ContentTypeAudioMpegURL = "audio/mpegurl"
	ContentTypeDASHXML      = "application/dash+xml"

	// Font types.
	ContentTypeFontWOFF  = "font/woff"
	ContentTypeFontWOFF2 = "font/woff2"
	ContentTypeFontTTF   = "font/ttf"
	ContentTypeFontOTF   = "font/otf"
)
